### PR TITLE
Fix for Xiaomi Aqara gateway

### PR DESCRIPTION
**Pull request by quarcko**
This gateway sends all his characteristics and services using lowercase letters.
Thus your library cannot identify some of information.
Quick fix to make uppercase-comparisons despite input being lowercase.

### CODE REVIEW

**Comment by jlusiardi** [comment]
Hi @quarcko 

thank you for your PR, but we have to fix the errors in the tests first. Can you give me an example what the Xiaomi Aqara exactly returns? I guess just making stuff upper case in the place you propse can't work all the way down, because the input may also be an integer.

Regards
Joachim

**Comment by quarcko** [comment]
Here is a diff between output with 'upper()' and without:
https://www.diffchecker.com/KH5pLojQ

I think i just overreacted with it. It is enough to make 'upper()' only in get_short()
of both characteristics and service types... no need to alter __getitem__, it still works as expected.

but:
FAIL: test_get_short (tests.characteristicsTypes_test.TestCharacteristicsTypes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/jlusiardi/homekit_python/tests/characteristicsTypes_test.py", line 51, in test_get_short
    self.assertEqual(CharacteristicsTypes.get_short('1a'), 'Unknown Characteristic 1a')
AssertionError: 'lock-management.auto-secure-timeout' != 'Unknown Characteristic 1a'
- lock-management.auto-secure-timeout
+ Unknown Characteristic 1a

This test is strange, you seem that on purpose do not allow 1a to be resolved like 1A? why?

**Comment by jlusiardi** [comment]
good point, not sure, can you extend the pull request like this:
```
        self.assertEqual(CharacteristicsTypes.get_short('1a'), 'lock-management.auto-secure-timeout')
```
Perhaps we should check if anything being a UUID is ok upper and lower case

**Comment by jlusiardi** [comment]
Thank you!

**Pull request merged**
