### PR TITLE
Convert to using exceptions

### PR DESCRIPTION
**Pull request by mjg59**
Raise exceptions when we hit an error rather than exiting. This allows
applications to handle failures more cleanly.

### CODE REVIEW

**Comment by jlusiardi** [comment]
Thanks a lot. Makes integrating easier, I guess?

**Comment by jlusiardi** [comment]
I will perform a new pypy release when I am back at my workstation.

**Comment by mjg59** [comment]
@jlusiardi Yup, this way Home Assistant can display errors when pairing fails

**Comment by jlusiardi** [comment]
Done the release. By the way, do you have access to homekit devices to test with this code? Especially to test the CLI version of the commands as described in the readme.

**Comment by mjg59** [comment]
I have a couple that I've been using for testing

**Comment by jlusiardi** [comment]
would be nice, to add to the list of tested device to show it is compatible

**Comment by jlusiardi** [comment]
would be nice, to add to the list of tested device to show it is compatible

**Pull request merged**
