### PR TITLE
Fix secure HTTP communication

### PR DESCRIPTION
**Pull request by mjg59**
We need to send \r\n as a separator, not \n

### CODE REVIEW

**Comment by jlusiardi** [comment]
Indeed the rfc says CRLF :)

**Comment by mjg59** [comment]
Thanks! Any chance you can push a new release to Pypi? I'm finishing up support for Homekit devices in Home Assistant.

**Comment by jlusiardi** [comment]
Ok, can u give it a try with pypi? version 0.5 should be there.

**Comment by mjg59** [comment]
Perfect, thank you!

**Pull request merged**
