### PR TITLE
Create Aqara Hub.md

### PR DESCRIPTION
**Pull request by benasse**

### CODE REVIEW

**Comment by benasse** [comment]
Is it normal that the indexes to go directly from 1 to 3?
It seems that the Aquara Cube is not exposed via homekit, am I missing something?

**Comment by Jc2k** [comment]
The indexes are up to the manufacturer - as long as they are consistent for that bridge and pairing they may well not be sequential.

**Comment by Jc2k** [comment]
It does look like the hub just isn’t exposing your Cube as a homekit device, unfortunately

**Comment by benasse** [comment]
ok thank you for the answer, I will use zigbee2mqtt to interact with the cube then.

**Comment by jlusiardi** [comment]
Thank you @benasse!

**Pull request merged**
