### PR TITLE
Fix 89 decryption failure not mapped to an appropriate error

### PR DESCRIPTION
**Pull request by jlusiardi**

### CODE REVIEW

**Comment by Jc2k** [comment]
On train atm and looking from phone so excuse my terseness and typos!

Looks good - 2 things I want to think about:

* Does this needs a change in Session as well? Look at how AccessoryNotFound is handled in there - it does self.session.close.

 * What happens if you close a socket that is already disconnected? I have a vague memory that closing an old socket can fail in weird ways. Should we try/except it and mask any OSError just in case?

**Comment by jlusiardi** [comment]
Yeah try/except for OSError is surely a good way.

I am not sure what is exactly meant with the reference to AccessoryNotFound though. Can you please elaborate?

**Comment by Jc2k** [comment]
I think these 2 lines show what I mean?

 * https://github.com/jlusiardi/homekit_python/blob/master/homekit/controller.py#L275
 * https://github.com/jlusiardi/homekit_python/blob/master/homekit/controller.py#L308

Without that we'll potentially introduce another form of #90?

**Comment by jlusiardi** [comment]
Ah I see. Have a look again ;)

**Comment by Jc2k** [comment]
Nice, LGTM 👍

**Pull request merged**
