### PR TITLE
Remove padding whitespace to satisfy Tado

### LINKED ISSUE #181: get_events fails for Tado Internet Bridge
I am not sure if that is a known problem.
I have just bought a Tado system and `homekit` module has worked like a charm to pair up with it and then to query accessories and control them.

```
$ python3 -m homekit.get_accessories -f test.homekit -a tado
1.1: >accessory-information<
  1.2: tado Internet Bridge ............ () >name< [pr]
  1.3: tado () >manufacturer< [pr]
  1.4: ............ () >serial-number< [pr]
  1.5: IB01 () >model< [pr]
  1.6: 60.6 () >firmware.revision< [pr]
  1.7:  () >identify< [pw]
1.8: >Unknown Service: E44673A0-247B-4360-8A76-DB9DA69C0100<
  1.9:  () >Unknown Characteristic E44673A0-247B-4360-8A76-DB9DA69C0101< [pw]
2.1: >accessory-information<
  2.2: tado Smart Radiator Thermostat ............ () >name< [pr]
  2.3: tado () >manufacturer< [pr]
  2.4: ............ () >serial-number< [pr]
  2.5: SRT01 () >model< [pr]
  2.6: 54.1 () >firmware.revision< [pr]
  2.7:  () >identify< [pw]
2.8: >Unknown Service: E44673A0-247B-4360-8A76-DB9DA69C0100<
  2.9:  () >Unknown Characteristic E44673A0-247B-4360-8A76-DB9DA69C0101< [pw]
2.10: >thermostat<
  2.11: tado Smart Radiator Thermostat ............ () >name< [pr]
  2.12: 1 () >heating-cooling.current< [pr,ev]
  2.13: 1 () >heating-cooling.target< [pr,pw,ev]
  2.14: 20.8 () >temperature.current< [pr,ev]
  2.15: 25 () >temperature.target< [pr,pw,ev]
  2.16: 0 () >temperature.units< [pr,pw,ev]
  2.17: 51 () >relative-humidity.current< [pr,ev]
```

Everything is working fine except for `get_events`. I was hoping I could avoid active polling temperatures and it seems homekit has `get_events` that should just keep on getting updated when new value comes in.

I have modified to see the payload that comes back and it seems empty:

```
2020-04-03 16:12:17,390 ip_implementation.py:0445 DEBUG session established
2020-04-03 16:12:17,391 secure_http.py:0073 DEBUG handle request: b'PUT /characteristics HTTP/1.1\r\nHost: 192.168.1.20:80\r\nContent-Type: application/hap+json\r\nContent-Length: 56\r\n\r\n{"characteristics": [{"aid": 2, "iid": 14, "ev": true}]}'
Session closed after receiving malformed response from device (bytearray(b''))
2020-04-03 16:12:17,411 get_events.py:0073 DEBUG Session closed after receiving malformed response from device (bytearray(b''))
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/homekit/controller/ip_implementation.py", line 313, in get_events
    data = json.loads(body.decode())
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/homekit/get_events.py", line 68, in <module>
    results = pairing.get_events(characteristics, func, max_events=args.eventCount, max_seconds=args.secondsCount)
  File "/usr/local/lib/python3.7/dist-packages/homekit/controller/ip_implementation.py", line 317, in get_events
    raise AccessoryDisconnectedError(f"Session closed after receiving malformed response from device ({body})")
homekit.exceptions.AccessoryDisconnectedError: Session closed after receiving malformed response from device (bytearray(b''))
```

I couldn't find anyone with similar issue around and I don't have any other HomeKit devices to check if the issue is with Tado bridge or is there something I am doing wrong.

### PR DESCRIPTION
**Pull request by elmopl**
Taking iPhone requests as source of truth about the format of json payloads
there should be no whitespace after comma (or anywhere that would be just spacing).
Some devices (like Tado Internet Bridge) are really fussy about that, and sending
json payload in Python's standard formatting will cause it to return error.
I.e. sending perfectly valid json:
    {"characteristics":[{"iid":15, "aid":2, "ev":true}]}
will not work, while:
    {"characteristics":[{"iid":15,"aid":2,"ev":true}]}
is accepted.

Fixes #181

### CODE REVIEW

**Comment by jlusiardi** [comment]
another question: why should we add `, separators=(',', ':')` only to this occurrence of `json.dumps`?

or even better: why does tado work on other payloads but not on this one?

**Comment by jlusiardi** [comment]
I just merged this PR into a branch and added some tests:
https://github.com/jlusiardi/homekit_python/tree/fix_181_testing_and_merging

What do you think? @elmopl can you please test with this branch?

**Comment by jlusiardi** [comment]
Ah I forget  `/resource`. Thanks! Could you add a test for that as I did for the 2 others?

**Comment by elmopl** [comment]
Run some tests:

```pi@raspberrypi:~ $ PYTHONPATH=homekit_python/ python3 -m homekit.put_characteristic -f test.homekit -a tado -c 2.15 25
pi@raspberrypi:~ $ PYTHONPATH=homekit_python/ python3 -m homekit.get_characteristic -f test.homekit -a tado -c 2.15
{
    "2.15": {
        "value": 25
    }
}
pi@raspberrypi:~ $ PYTHONPATH=homekit_python/ python3 -m homekit.put_characteristic -f test.homekit -a tado -c 2.15 23
pi@raspberrypi:~ $ PYTHONPATH=homekit_python/ python3 -m homekit.get_characteristic -f test.homekit -a tado -c 2.15
{
    "2.15": {
        "value": 23
    }
}

pi@raspberrypi:~ $ PYTHONPATH=homekit_python/ python3 -m homekit.get_events -f test.homekit -a tado -c 2.15 -c 2.16 -c 2.13 -c 2.12 -c 2.14 -c 2.17
event for 2.15: 25
event for 2.12: 0
event for 2.13: 0
event for 2.12: 1
event for 2.13: 1
event for 2.15: 23

```

All while checking that TRV actually gets updated + last test was with me changing TRV manually.


I have merged `fix_181_testing_and_merging` and pulled out `json.dumps` with comment to be in just one place.

Added test for `get_resource`.

**Comment by jlusiardi** [comment]
cool thank you!

**Pull request merged**
