### PR TITLE
Fix Netatmo Relay crash

### PR DESCRIPTION
**Pull request by LucaKaufmann**
Discovery was crashing when running it with a Netatmo Relay on the network. This should fix that crash but more work might be required to get Netatmo running.

### CODE REVIEW

**Comment by lboue** [comment]
Here is a wireshark capture of a MDNS 'Standard query response' send by the Netatmo Relay:

```
    Answers
        _hap._tcp.local: type PTR, class IN, Thermostat._hap._tcp.local
            Name: _hap._tcp.local
            Type: PTR (domain name PoinTeR) (12)
            .000 0000 0000 0001 = Class: IN (0x0001)
            0... .... .... .... = Cache flush: False
            Time to live: 4500
            Data length: 13
            Domain Name: Thermostat._hap._tcp.local
    Additional records
        Thermostat._hap._tcp.local: type TXT, class IN, cache flush
            Name: Thermostat._hap._tcp.local
            Type: TXT (Text strings) (16)
            .000 0000 0000 0001 = Class: IN (0x0001)
            1... .... .... .... = Cache flush: True
            Time to live: 4500
            Data length: 92
            TXT Length: 4
            TXT: S#=1
            TXT Length: 4
            TXT: ff=1
            TXT Length: 4
            TXT: sf=0
            TXT Length: 6
            TXT: pv=1.1
            TXT Length: 17
            TXT: md=Netatmo Relay
            TXT Length: 20
            TXT: id=F0:07:45:********
            TXT Length: 19
            TXT: na_tkn=e005bee****
            TXT Length: 4
            TXT: ci=2
            TXT Length: 5
            TXT: C#=12
```

I notice a C# value a the end.

**Comment by jlusiardi** [comment]
Hi,

as far as I understand the specification from Apple on page 69, the keys in question here (**c#** and **s#*) should be written like that and not use upper case letters. So the data from @lboue shows both keys with upper case letters but they are not really missing. @LucaKaufmann can you confirm with your Netatmo Relay?

Regard
Joachim

**Comment by LucaKaufmann** [comment]
@jlusiardi yep that seems to be it, the keys are upper case instead of lower case

**Comment by lboue** [comment]
Thanks for the response. Can you change the code to allow both upper and lower case letters?
I will try to contact Netatmo to fix this. 

Regards

**Comment by jlusiardi** [comment]
I will have a look into it in branch **fix_54_Netatmo_Relay_crash**

**Comment by jlusiardi** [comment]
hey there,

I just pushed some code to work on the issue to the branch. Can you test if the Netatmo relay can now be discovered?

Regards
Joachim

**Comment by lboue** [comment]
Thanks a lot it works fine now 👍

```
pi@raspberrypi:~ $ cd /tmp/
pi@raspberrypi:/tmp $ git clone https://github.com/jlusiardi/homekit_python/
Clonage dans 'homekit_python'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 1458 (delta 0), reused 2 (delta 0), pack-reused 1452
RÃ©ception d'objets: 100% (1458/1458), 662.89 KiB | 444.00 KiB/s, fait.
RÃ©solution des deltas: 100% (1023/1023), fait.
pi@raspberrypi:/tmp $ cd homekit_python/
pi@raspberrypi:/tmp/homekit_python $ git clone https://github.com/jlusiardi/homekit_python/^C
pi@raspberrypi:/tmp/homekit_python $ git checkout fix_54_Netatmo_Relay_crash
La branche fix_54_Netatmo_Relay_crash est paramÃ©trÃ©e pour suivre la branche distante fix_54_Netatmo_Relay_crash depuis origin.
Basculement sur la nouvelle branche 'fix_54_Netatmo_Relay_crash'

pi@raspberrypi:/tmp/homekit_python $ pip3 install --user homekit
Requirement already satisfied: homekit in /home/pi/.local/lib/python3.5/site-packages
Requirement already satisfied: py25519 in /home/pi/.local/lib/python3.5/site-packages (from homekit)
Requirement already satisfied: ed25519 in /home/pi/.local/lib/python3.5/site-packages (from homekit)
Requirement already satisfied: zeroconf in /home/pi/.local/lib/python3.5/site-packages (from homekit)
Requirement already satisfied: gmpy2 in /home/pi/.local/lib/python3.5/site-packages (from homekit)
Requirement already satisfied: hkdf in /home/pi/.local/lib/python3.5/site-packages (from homekit)
Requirement already satisfied: cffi-utils in /home/pi/.local/lib/python3.5/site-packages (from py25519->homekit)
Requirement already satisfied: netifaces!=0.10.5 in /home/pi/.local/lib/python3.5/site-packages (from zeroconf->homekit)
Requirement already satisfied: cffi>=1.0.0 in /home/pi/.local/lib/python3.5/site-packages (from cffi-utils->py25519->homekit)
Requirement already satisfied: pycparser in /home/pi/.local/lib/python3.5/site-packages (from cffi>=1.0.0->cffi-utils->py25519->homekit)
You are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


pi@raspberrypi:/tmp/homekit_python $ python3 -m homekit.discover
Name: Philips hue - ABCDE._hap._tcp.local.
Url: http://192.168.1.19:8080
Configuration number (c#): 14
Feature Flags (ff): Supports Pairing (Flag: 1)
Device ID (id): EA:9B:7A:AB:CD:ED
Model Name (md): BSB002
Protocol Version (pv): 1.1
State Number (s#): 1
Status Flags (sf): 0
Category Identifier (ci): Bridge (Id: 2)

Name: Thermostat._hap._tcp.local.
Url: http://192.168.1.58:5001
Configuration number (c#): 12
Feature Flags (ff): Supports Pairing (Flag: 1)
Device ID (id): F0:07:45:AB:CD:EA
Model Name (md): Netatmo Relay
Protocol Version (pv): 1.1
State Number (s#): 1
Status Flags (sf): 0
Category Identifier (ci): Bridge (Id: 2)

Name: Homebridge-9D05._hap._tcp.local.
Url: http://192.168.1.91:51826
Configuration number (c#): 18072
Feature Flags (ff): Paired (Flag: 0)
Device ID (id): CC:21:3E:E4:DE:50
Model Name (md): Homebridge
Protocol Version (pv): 1.0
State Number (s#): 1
Status Flags (sf): 0
Category Identifier (ci): Bridge (Id: 2)
```


Regards

**Comment by jlusiardi** [comment]
Hi @lboue,

glad to read this. Can you also check if the other use case work on the Netatmo relay?

Regards
Joachim

**Comment by jlusiardi** [comment]
Merged to master. Thanks @LucaKaufmann for the hint!

**Comment by LucaKaufmann** [comment]
Looks good from my side as well, thanks! I'll go ahead and close this PR

**Comment by lboue** [comment]
Works fine for the [Legrand Gateway by Netatmo](https://www.netatmo.com/fr-FR/partners/legrand) too. Tested tonight.

```
pi@raspberrypi:/tmp/homekit_python $ python3 -m homekit.discover
...

Name: Legrand Gateway._hap._tcp.local.
Url: http://192.168.1.xx:5001
Configuration number (c#): 2
Feature Flags (ff): Supports Pairing (Flag: 1)
Device ID (id): E9:64:E0:AB:CD:EB
Model Name (md): Legrand Gateway
Protocol Version (pv): 1.0
State Number (s#): 1
Status Flags (sf): 0
Category Identifier (ci): Bridge (Id: 2)
```

Regards,
Ludovic

**Pull request closed without merging**
