### PR TITLE
Enforce ordering of TLVs in encode_dict

### PR DESCRIPTION
**Pull request by mjg59**
Some devices (such as the Hue hub) are sensitive to the ordering of the
TLVs in encrypted messages, and misparse requests if they aren't in the
same order as the Apple implementation. Use collections.OrderedDict to
enforce this.

### CODE REVIEW

**Comment by mjg59** [comment]
https://github.com/jlusiardi/homekit_python/issues/35

**Comment by jlusiardi** [comment]
hey,

thanks for your contribution. Would you mind looking if TLV.encode_list would suit this as well?

Regard
Joachim

**Comment by mjg59** [comment]
Ah yes that looks simpler - how's this version

**Comment by jlusiardi** [comment]
looks fine

**Pull request merged**
