### PR TITLE
Added new category definitions for new Homekit accessory categories

### PR DESCRIPTION
**Pull request by netmanchris**
Added new categories to address https://github.com/jlusiardi/homekit_python/issues/131

### CODE REVIEW

**Comment by jlusiardi** [comment]
I just changed the comment starting with '#' to '# ' to fix the tests.

**Comment by jlusiardi** [comment]
@netmanchris can you please change this PR to go into branch `fix_131_add_new_categories_characteristics_and_services` instead of master?

**Comment by netmanchris** [comment]
Moved PR to fix_131_add_new_categories_characteristics_and_services branch

**Comment by jlusiardi** [comment]
cool thank you!

**Pull request merged**
