### PR TITLE
Add tests for BLE implementation of controller

### PR DESCRIPTION
**Pull request by Jc2k**
This is a massive WIP so you can get a sense of what i'm working on - i'm not sure if it will even run anywhere but my VM yet, and i need to do some more real integration tests to make sure im locking in the working behaviours.

I've started on top of #61  as the changes in there make things easier to test. There are a few other tweaks to make it easier to test. The real interesting commit is  e461bc8.

So far can pair, pair verify, enumerate services and get_characteristics.

The big gap is exposing data types on my fake bluetooth device. Everything is mapped to unknown data types right now, so no floats, bools, etc.

Will be polishing this up over the next few days.

### CODE REVIEW

**Comment by Jc2k** [comment]
Now have a test for put_characteristic, and basic data type formatting is working.

Going to rebase my chain of PR's again now.

**Comment by Jc2k** [comment]
Rebased, and tests still pass.

Still, these rebases are getting painful.

**Comment by Jc2k** [comment]
Have been running the ble tests directly - theres a weird conflict when travis runs all of them that im still trying to chase down. Annoying.

**Comment by Jc2k** [comment]
Coverage up to 80.89% on ble_implementation.py, 79.4% overall. Lots of low hanging fruit still to go as well.

Plan to add some tests for parsing mfr data next, and add some tests for the negative cases too.

Turned on coveralls on my repo as well so I can see how i'm doing - https://coveralls.io/github/Jc2k/homekit_python

**Comment by Jc2k** [comment]
I have rebased these this morning and tidied the commits up a bit - i've added a justification for each one as well. Hopefully this will help with reviewing.

**Comment by jlusiardi** [comment]
Hi,

Some thoughts:

-  Would it be possible to keep the BLE related stuff all close together in one submodule? in your version it is in `homekit/ble_impl/*` and in `homekit/controller/ble_impl.py`. Why not make it `homekit/controller/ble_impl/*` and only export the required stuff via `homekit/controller/ble_impl/__init__.py`? 

- Can you merge my comments from https://github.com/jlusiardi/homekit_python/tree/fix_68_discover_ble_fixes into your code?

- The `PairingService` looks odd to me. What is it needed for? And you mean the service defined on Page 57, right?

Regards
Joachim

**Comment by Jc2k** [comment]
Of course - happy to put the code wherever you see fit. Would have put it under homekit/controller/ble or something if it was my project - the impl seems superfluous. It’s only named like it currently is because of because I saw the http_impl / zeroconf_impl folders and it felt similar to them.

I’d be tempted to move it all into controller like you said and break up ble_implementation into smaller parts (later in another pr).

Will do comments now.

PairingService is indeed odd. For the most part my virtual BT device is able to export your service models directly, including metadata used to find characteristics in the first place. I needed some of that logic for the pairing service (so that we can find the right fake characteristic) but after that the protocol for them is very different and needs special casing. I’ll see if I can special case the entire service to not use any model code at all, then drop the model changes...

**Comment by Jc2k** [comment]
I've incorporated your PR comments I think. Have added more comments in places as well.

Just looking at tests + PairingService now.

**Comment by Jc2k** [comment]
Have just dropped the need for the PairingService and the 2 pairing characteristics, so they are now gone from this PR. Hopefully the tests will still pass.

Will make the ble_impl change from #67 and rebase upwards.

**Comment by Jc2k** [comment]
The big bit is done - the ble_impl folder is now inside controller.

Tomorrow i'll move ble_implementation.py into it as well - but this will have to be on top of the tests.

**Comment by Jc2k** [comment]
Side note - the first commit in this branch (also available seperately in #67) is kind of large, but I tried to learn my lesson and for the most part the other commits in this branch have decent commit messages and try to be independent of each other.

I could try to break it up if the review is still too painful, but it will be hard to ensure every commit is in a working state before there are tests in place, so not sure its that useful, really.

**Comment by Jc2k** [comment]
That's really good news. Let me know if there any tweaks you'd like me to make as well. I definitely have ideas for follow ups:

 * Testing the CLI scripts themselves
 * Refactoring the accessoryserver stuff a bit so that the test code that uses it for BLE devices is a bit nicer
 * Seperating out session into its own module
 * Adding protocol serializers and deserializers to reduce the amount of boiler plate bytearray stuff we do

As well as the outstanding bugs and features of course!

**Comment by Jc2k** [comment]
Yay!

**Pull request merged**
