### PR TITLE
Automatically close session on network failure

### LINKED ISSUE #90: Controller instance cannot recover from HTTP failure (IP backend)
https://github.com/home-assistant/home-assistant/issues/18949

Reviewing the code, it looks like Session creates a single connection to an IP/Port and the same underlying socket and port is then reused. So the controller only works as long as the TCP session stays open. It looks like this can time out:

```
2019-01-11 17:03:08 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.p1eu_4 fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 349, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/homekit_controller/__init__.py", line 197, in update
    data = pairing.list_accessories_and_characteristics()
  File "/config/deps/lib/python3.6/site-packages/homekit/controller.py", line 273, in list_accessories_and_characteristics
    response = self.session.get('/accessories')
  File "/config/deps/lib/python3.6/site-packages/homekit/controller.py", line 573, in get
    return self.sec_http.get(url)
  File "/config/deps/lib/python3.6/site-packages/homekit/http_impl/secure_http.py", line 65, in get
    return self._handle_request(data)
  File "/config/deps/lib/python3.6/site-packages/homekit/http_impl/secure_http.py", line 89, in _handle_request
    return self._read_response()
  File "/config/deps/lib/python3.6/site-packages/homekit/http_impl/secure_http.py", line 131, in _read_response
    data = self.sock.recv(exp_len)
socket.timeout: timed out
```

And then if the API is used again:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 349, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/homekit_controller/__init__.py", line 197, in update
    data = pairing.list_accessories_and_characteristics()
  File "/config/deps/lib/python3.6/site-packages/homekit/controller.py", line 273, in list_accessories_and_characteristics
    response = self.session.get('/accessories')
  File "/config/deps/lib/python3.6/site-packages/homekit/controller.py", line 573, in get
    return self.sec_http.get(url)
  File "/config/deps/lib/python3.6/site-packages/homekit/http_impl/secure_http.py", line 65, in get
    return self._handle_request(data)
  File "/config/deps/lib/python3.6/site-packages/homekit/http_impl/secure_http.py", line 88, in _handle_request
    self.sock.send(len_bytes + ciper_and_mac[0] + ciper_and_mac[1])
BrokenPipeError: [Errno 32] Broken pipe
```

We need to handle socket errors, and automatically close the session when they happen. I'm imagining catching the socket error in Session:

```
    def get(self, url):
        """
        Perform HTTP get via the encrypted session.
        :param url: The url to request
        :return: a homekit.http_impl.HttpResponse object
        """
        try:
            return self.sec_http.get(url)
        except OSError:
            raise exceptions.DeviceConnectionError(str(e))
```

And additionally adding some guards to session usage like this:

```
    def list_accessories_and_characteristics(self):
        """
        This retrieves a current set of accessories and characteristics behind this pairing.

        :return: the accessory data as described in the spec on page 73 and following
        :raises AccessoryNotFoundError: if the device can not be found via zeroconf
        """
        if not self.session:
            self.session = Session(self.pairing_data)

        try:
            response = self.session.get('/accessories')
            tmp = response.read().decode()
        except:
            self.session.close()
            self.session = None
            raise

        accessories = json.loads(tmp)['accessories']
        self.pairing_data['accessories'] = accessories
        return accessories
```

This won't fix the problem (we can't stop a connection dropping) but it will mean we recover from it.

### PR DESCRIPTION
**Pull request by Jc2k**
Need to do some testing with this tonight (don't have any devices to hand), but in theory fixes #90. What do you think?

### CODE REVIEW

**Comment by Jc2k** [comment]
This seems to be working in my environment to some extent - haven't seen timeouts, but if i interupt a session (hard power off accessory) it is now able to recover.

**Comment by Jc2k** [comment]
Added some code to handle JSONDecodeError as well (seem to get empty or malformed JSON when the network connection is interrupted).

Have managed to get feedback from HA users saying this helps now - I need to get this PR into master and released so I can submit a corresponding PR to HA. Is that something that could happen? Cheers.

**Comment by jlusiardi** [comment]
yes should be possible to handout 0.12.1 or 0.13. This will then also include the fix for #87

I'll try to do this on monday

**Comment by Jc2k** [comment]
Excellent news!

Re: HASS, the code is structured weirdly and it took me a while to figure out how it all goes together. There are 2 homekit modules, 'ours' is `homekit_controller` (see [here](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/homekit_controller/__init__.py)). `homekit` is a slightly more `asyncio` version of accessoryserver and exports HASS accessories to homekit enabled phones etc. It doesn't have a controller part at all. And its implemented by a different team. We are the only ones talking to homekit devices.

Then there is an additional component to map the device classes to homekit categories. For example a light or a switch. There are:

 * alarm_control_panel
 * climate
 * cover
 * light
 * lock
 * switch

And possibly one more i've forgotten.

Oh and one of my branches adds an Eve Motion and maps it to a binary_sensor. You can see one of those [here](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/light/homekit_controller.py).

[This branch](https://github.com/home-assistant/home-assistant/compare/dev...Jc2k:homekit_controller_next) has all my oustranding patches in for them, but only the oldest patch in the branch is ready. I'm very close to having my Eve devices in home assistant, and to removing the polling that it currently does in favour of events.

**Comment by Jc2k** [comment]
Thanks for the update @swampyclark. I think thats good news, combined with the HA patch I have in mind we should be in a good place.

To confirm though - despite 3 errors going off at the same time, it does recover?

Are the 3 devices connected to the same hub, and thats what the connection is to? So there are 3 entities sharing the same TCP connection to a hub? (Want to be sure we arent somehow breaking sessions between entirely unrelated devices!)

**Pull request merged**
